name: Build & Deploy

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run Build & Deploy (and Tests if necessary)
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version-file: .nvmrc

      - name: Restore Build Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: './node_modules/.astro'
          key: astro-cache-${{ github.ref }}

      - name: Install dependencies
        run: npm ci

      - name: Build your site
        run: npm run build

      - name: Test with Lighthouse CI
        uses: treosh/lighthouse-ci-action@2f8dda6cf4de7d73b29853c3f29e73a01e297bd8 # v12
        if: ${{ github.event_name == 'pull_request' }}
        with:
          configPath: './.lighthouserc.json'
          temporaryPublicStorage: true

      - name: Upload files to Cloudflare Pages
        uses: cloudflare/wrangler-action@f84a562284fc78278ff9052435d9526f9c718361 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=sngr-my-id
